### ISSUE TITLE
(Meta) Angular can be built and served using Bazel

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/rules_dart#3]
Meta issue for being able to build and serve Angular Dart applications using Bazel:
- [ ] Source generation works using Bazel, and is tested
- [ ] Angular template generation works using Bazel, and is tested
- [x] It is possible to "serve" a pre-built Angular Dart project (i.e. bazel build already happened)

Nice to haves/stretch goals:
- [x] A simple file-watcher (?) that re-runs bazel build until we have iBlaze
- [x] DDC and Analyzer summaries work using Bazel

_Will keep adding to this as we expand the set of issues_
